import Bhaktiimg1 from '/assets/img/Bhakti1.webp'
import Bhaktiimg2 from '/assets/img/Bhakti2.webp'
import Bhaktiimg3 from '/assets/img/Bhakti3.webp'
import Bhaktiimg4 from '/assets/img/Bhakti4.webp'
import Bhaktiimg5 from '/assets/img/Bhakti5.webp'
import Bhaktiimg6 from '/assets/img/Bhakti6.webp'
import Bhaktiimg7 from '/assets/img/Bhakti7.webp'
import Bhaktiimg8 from '/assets/img/Bhakti8.webp'
import Bhaktiimg9 from '/assets/img/Bhakti9.webp'
import Bhaktiimg10 from '/assets/img/Bhakti10.webp'
import Bhaktiimg11 from '/assets/img/Bhakti11.webp'
import Bhaktiimg12 from '/assets/img/Bhakti12.webp'

import Divineimg1 from '/assets/img/Divine1.png'
import Divineimg2 from '/assets/img/Divine1.png'
import Divineimg3 from '/assets/img/Divine1.png'
import Divineimg4 from '/assets/img/Divine1.png'
import Divineimg5 from '/assets/img/Divine1.png'
import Divineimg6 from '/assets/img/Divine1.png' 

import Gifting1 from '/assets/img/Gifting1.png'
import Gifting2 from '/assets/img/Gifting2.png'
import Gifting3 from '/assets/img/Gifting3.png'
import Gifting4 from '/assets/img/Gifting4.png'
import Gifting5 from '/assets/img/Gifting5.png'
import Gifting6 from '/assets/img/Gifting6.png'
import Gifting7 from '/assets/img/Gifting7.png'
import Gifting8 from '/assets/img/Gifting8.png'
import Gifting9 from '/assets/img/Gifting9.png'
import Gifting10 from '/assets/img/Gifting10.png'

import RitualImg1 from '/assets/img/Ritual1.webp'
import RitualImg2 from '/assets/img/Ritual2.webp'
import RitualImg3 from '/assets/img/Ritual3.webp'
import RitualImg4 from '/assets/img/Ritual4.webp'
import RitualImg5 from '/assets/img/Ritual5.webp'

import SacredImg1 from '/assets/img/Sacred1.webp'
import SacredImg2 from '/assets/img/Sacred2.webp'
import SacredImg3 from '/assets/img/Sacred3.webp'
import SacredImg4 from '/assets/img/Sacred4.webp'
import SacredImg5 from '/assets/img/Sacred5.webp'
import SacredImg6 from '/assets/img/Sacred6.webp'
import SacredImg7 from '/assets/img/Sacred7.webp'

import SacredScentsImg1 from '/assets/img/SacredScents1.webp'
import SacredScentsImg2 from '/assets/img/SacredScents2.webp'
import SacredScentsImg3 from '/assets/img/SacredScents3.webp'
import SacredScentsImg4 from '/assets/img/SacredScents4.webp'
import SacredScentsImg5 from '/assets/img/SacredScents5.webp'
import SacredScentsImg6 from '/assets/img/SacredScents6.webp'
import SacredScentsImg7 from '/assets/img/SacredScents7.webp'
import SacredScentsImg8 from '/assets/img/SacredScents8.webp'

import SringarBoxImg1 from '/assets/img/SringarBox1.webp'
import SringarBoxImg2 from '/assets/img/SringarBox2.webp'
import SringarBoxImg3 from '/assets/img/SringarBox3.webp'

import TempleDecorImg1 from '/assets/img/TempleDecor1.webp'
import TempleDecorImg2 from '/assets/img/TempleDecor2.webp'
import TempleDecorImg3 from '/assets/img/TempleDecor3.webp'
import TempleDecorImg4 from '/assets/img/TempleDecor4.webp'

const Product = [
    { id : 1, name: 'arvind', thumbnailImage : Bhaktiimg1, imges : Bhaktiimg1, title : "Soft & Cuddly Bhakti Plush", description : "My Little Deities is a project focused on making figures from Hindu tradition accessible and approachable for young children through a line of soft and cuddly plush toys. These Bhakti Plush characters will be designed with simple, endearing features to capture the essence of each deity or figure in a way that resonates with kids. The goal is to provide a gentle introduction to faith and culture through a medium that children naturally love and connect with", price : 700, size : "27 x 17 x 8 cm ",createdAt: '2024-08-12',category: 'Bhakti', popularity: 70},
    { id : 2, name: 'arvind', thumbnailImage : Bhaktiimg2, imges : Bhaktiimg2, title : "Soft & Cuddly Bhakti Plush", description : "My Little Deities is a project focused on making figures from Hindu tradition accessible and approachable for young children through a line of soft and cuddly plush toys. These Bhakti Plush characters will be designed with simple, endearing features to capture the essence of each deity or figure in a way that resonates with kids. The goal is to provide a gentle introduction to faith and culture through a medium that children naturally love and connect with", price : 300, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-17',category: 'Bhakti', popularity: 100},
    { id : 3, name: 'arvind', thumbnailImage : Bhaktiimg3, imges : Bhaktiimg3, title : "Soft & Cuddly Bhakti Plush", description : "My Little Deities is a project focused on making figures from Hindu tradition accessible and approachable for young children through a line of soft and cuddly plush toys. These Bhakti Plush characters will be designed with simple, endearing features to capture the essence of each deity or figure in a way that resonates with kids. The goal is to provide a gentle introduction to faith and culture through a medium that children naturally love and connect with", price : 400, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-19',category: 'Bhakti', popularity: 190},
    { id : 4, name: 'arvind', thumbnailImage : Bhaktiimg4, imges : Bhaktiimg4, title : "Soft & Cuddly Bhakti Plush", description : "My Little Deities is a project focused on making figures from Hindu tradition accessible and approachable for young children through a line of soft and cuddly plush toys. These Bhakti Plush characters will be designed with simple, endearing features to capture the essence of each deity or figure in a way that resonates with kids. The goal is to provide a gentle introduction to faith and culture through a medium that children naturally love and connect with", price : 500, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-21',category: 'Bhakti', popularity: 200},
    { id : 5, name: 'arvind', thumbnailImage : Bhaktiimg5, imges : Bhaktiimg5, title : "Soft & Cuddly Bhakti Plush", description : "My Little Deities is a project focused on making figures from Hindu tradition accessible and approachable for young children through a line of soft and cuddly plush toys. These Bhakti Plush characters will be designed with simple, endearing features to capture the essence of each deity or figure in a way that resonates with kids. The goal is to provide a gentle introduction to faith and culture through a medium that children naturally love and connect with", price : 1200,size : "27 x 17 x 8 cm" ,createdAt: '2024-08-22',category: 'Bhakti', popularity: 10},
    { id : 6, name: 'arvind', thumbnailImage : Bhaktiimg6, imges : Bhaktiimg6, title : "Soft & Cuddly Bhakti Plush", description : "My Little Deities is a project focused on making figures from Hindu tradition accessible and approachable for young children through a line of soft and cuddly plush toys. These Bhakti Plush characters will be designed with simple, endearing features to capture the essence of each deity or figure in a way that resonates with kids. The goal is to provide a gentle introduction to faith and culture through a medium that children naturally love and connect with", price : 320, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-27',category: 'Bhakti', popularity: 20},
    { id : 7, name: 'arvind', thumbnailImage : Bhaktiimg7, imges : Bhaktiimg7, title : "Soft & Cuddly Bhakti Plush", description : "My Little Deities is a project focused on making figures from Hindu tradition accessible and approachable for young children through a line of soft and cuddly plush toys. These Bhakti Plush characters will be designed with simple, endearing features to capture the essence of each deity or figure in a way that resonates with kids. The goal is to provide a gentle introduction to faith and culture through a medium that children naturally love and connect with", price : 110, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-28',category: 'Bhakti', popularity: 170 },
    { id : 8, name: 'arvind', thumbnailImage : Bhaktiimg8, imges : Bhaktiimg8, title : "Soft & Cuddly Bhakti Plush", description : "My Little Deities is a project focused on making figures from Hindu tradition accessible and approachable for young children through a line of soft and cuddly plush toys. These Bhakti Plush characters will be designed with simple, endearing features to capture the essence of each deity or figure in a way that resonates with kids. The goal is to provide a gentle introduction to faith and culture through a medium that children naturally love and connect with", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Bhakti', popularity: 390},
    { id : 9, name: 'arvind', thumbnailImage : Bhaktiimg9, imges : Bhaktiimg9, title : "Soft & Cuddly Bhakti Plush", description : "My Little Deities is a project focused on making figures from Hindu tradition accessible and approachable for young children through a line of soft and cuddly plush toys. These Bhakti Plush characters will be designed with simple, endearing features to capture the essence of each deity or figure in a way that resonates with kids. The goal is to provide a gentle introduction to faith and culture through a medium that children naturally love and connect with", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Bhakti', popularity: 390},
    { id : 10, name: 'arvind', thumbnailImage : Bhaktiimg10, imges : Bhaktiimg10, title : "Soft & Cuddly Bhakti Plush", description : "My Little Deities is a project focused on making figures from Hindu tradition accessible and approachable for young children through a line of soft and cuddly plush toys. These Bhakti Plush characters will be designed with simple, endearing features to capture the essence of each deity or figure in a way that resonates with kids. The goal is to provide a gentle introduction to faith and culture through a medium that children naturally love and connect with", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Bhakti', popularity: 390},
    { id : 11, name: 'arvind', thumbnailImage : Bhaktiimg11, imges : Bhaktiimg11, title : "Soft & Cuddly Bhakti Plush", description : "My Little Deities is a project focused on making figures from Hindu tradition accessible and approachable for young children through a line of soft and cuddly plush toys. These Bhakti Plush characters will be designed with simple, endearing features to capture the essence of each deity or figure in a way that resonates with kids. The goal is to provide a gentle introduction to faith and culture through a medium that children naturally love and connect with", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Bhakti', popularity: 390},
    { id : 12, name: 'arvind', thumbnailImage : Bhaktiimg12, imges : Bhaktiimg12, title : "Soft & Cuddly Bhakti Plush", description : "My Little Deities is a project focused on making figures from Hindu tradition accessible and approachable for young children through a line of soft and cuddly plush toys. These Bhakti Plush characters will be designed with simple, endearing features to capture the essence of each deity or figure in a way that resonates with kids. The goal is to provide a gentle introduction to faith and culture through a medium that children naturally love and connect with", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Bhakti', popularity: 390},
    { id : 13, name: 'arvind', thumbnailImage : Divineimg1, imges : Divineimg1, title : "Divine Oils & Itra", description : "Immerse yourself in our exquisite collection of Divine Oils and traditional Itra. Sourced for their purity and revered for their aromatic properties, these sacred scents have been used for centuries to enhance spiritual practices, promote well-being, and create a tranquil atmosphere. Explore our range of single-note essential oils and expertly blended itra, each carefully selected to elevate your senses and connect you with a sense of the divine", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Divine', popularity: 390},
    { id : 14, name: 'arvind', thumbnailImage : Divineimg2, imges : Divineimg2, title : "Divine Oils & Itra", description : "Immerse yourself in our exquisite collection of Divine Oils and traditional Itra. Sourced for their purity and revered for their aromatic properties, these sacred scents have been used for centuries to enhance spiritual practices, promote well-being, and create a tranquil atmosphere. Explore our range of single-note essential oils and expertly blended itra, each carefully selected to elevate your senses and connect you with a sense of the divine", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Divine', popularity: 390},
    { id : 15, name: 'arvind', thumbnailImage : Divineimg3, imges : Divineimg3, title : "Divine Oils & Itra", description : "Immerse yourself in our exquisite collection of Divine Oils and traditional Itra. Sourced for their purity and revered for their aromatic properties, these sacred scents have been used for centuries to enhance spiritual practices, promote well-being, and create a tranquil atmosphere. Explore our range of single-note essential oils and expertly blended itra, each carefully selected to elevate your senses and connect you with a sense of the divine", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Divine', popularity: 390},
    { id : 16, name: 'arvind', thumbnailImage : Divineimg4, imges : Divineimg4, title : "Divine Oils & Itra", description : "Immerse yourself in our exquisite collection of Divine Oils and traditional Itra. Sourced for their purity and revered for their aromatic properties, these sacred scents have been used for centuries to enhance spiritual practices, promote well-being, and create a tranquil atmosphere. Explore our range of single-note essential oils and expertly blended itra, each carefully selected to elevate your senses and connect you with a sense of the divine", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Divine', popularity: 390},
    { id : 17, name: 'arvind', thumbnailImage : Divineimg5, imges : Divineimg5, title : "Divine Oils & Itra", description : "Immerse yourself in our exquisite collection of Divine Oils and traditional Itra. Sourced for their purity and revered for their aromatic properties, these sacred scents have been used for centuries to enhance spiritual practices, promote well-being, and create a tranquil atmosphere. Explore our range of single-note essential oils and expertly blended itra, each carefully selected to elevate your senses and connect you with a sense of the divine", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Divine', popularity: 390},
    { id : 18, name: 'arvind', thumbnailImage : Divineimg6, imges : Divineimg6, title : "Divine Oils & Itra", description : "Immerse yourself in our exquisite collection of Divine Oils and traditional Itra. Sourced for their purity and revered for their aromatic properties, these sacred scents have been used for centuries to enhance spiritual practices, promote well-being, and create a tranquil atmosphere. Explore our range of single-note essential oils and expertly blended itra, each carefully selected to elevate your senses and connect you with a sense of the divine", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Divine', popularity: 390},
    { id : 19, name: 'arvind', thumbnailImage : Gifting1, imges : Gifting1, title : "Gifting & Utsav Collection", description : "Discover the perfect expression of joy and devotion with our Gifting & Utsav Collection. Whether you're marking a special milestone, celebrating a festive occasion, or simply sharing a heartfelt gesture, our curated selection offers thoughtful gifts and essential items to enhance every celebration. Explore a range of beautifully crafted products designed to bring happiness and spiritual warmth to your loved ones and your home.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Gifting', popularity: 390},
    { id : 20, name: 'arvind', thumbnailImage : Gifting2, imges : Gifting2, title : "Gifting & Utsav Collection", description : "Discover the perfect expression of joy and devotion with our Gifting & Utsav Collection. Whether you're marking a special milestone, celebrating a festive occasion, or simply sharing a heartfelt gesture, our curated selection offers thoughtful gifts and essential items to enhance every celebration. Explore a range of beautifully crafted products designed to bring happiness and spiritual warmth to your loved ones and your home.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Gifting', popularity: 390},
    { id : 21, name: 'arvind', thumbnailImage : Gifting3, imges : Gifting3, title : "Gifting & Utsav Collection", description : "Discover the perfect expression of joy and devotion with our Gifting & Utsav Collection. Whether you're marking a special milestone, celebrating a festive occasion, or simply sharing a heartfelt gesture, our curated selection offers thoughtful gifts and essential items to enhance every celebration. Explore a range of beautifully crafted products designed to bring happiness and spiritual warmth to your loved ones and your home.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Gifting', popularity: 390},
    { id : 22, name: 'arvind', thumbnailImage : Gifting4, imges : Gifting4, title : "Gifting & Utsav Collection", description : "Discover the perfect expression of joy and devotion with our Gifting & Utsav Collection. Whether you're marking a special milestone, celebrating a festive occasion, or simply sharing a heartfelt gesture, our curated selection offers thoughtful gifts and essential items to enhance every celebration. Explore a range of beautifully crafted products designed to bring happiness and spiritual warmth to your loved ones and your home.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Gifting', popularity: 390},
    { id : 23, name: 'arvind', thumbnailImage : Gifting5, imges : Gifting5, title : "Gifting & Utsav Collection", description : "Discover the perfect expression of joy and devotion with our Gifting & Utsav Collection. Whether you're marking a special milestone, celebrating a festive occasion, or simply sharing a heartfelt gesture, our curated selection offers thoughtful gifts and essential items to enhance every celebration. Explore a range of beautifully crafted products designed to bring happiness and spiritual warmth to your loved ones and your home.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Gifting', popularity: 390},
    { id : 24, name: 'arvind', thumbnailImage : Gifting6, imges : Gifting6, title : "Gifting & Utsav Collection", description : "Discover the perfect expression of joy and devotion with our Gifting & Utsav Collection. Whether you're marking a special milestone, celebrating a festive occasion, or simply sharing a heartfelt gesture, our curated selection offers thoughtful gifts and essential items to enhance every celebration. Explore a range of beautifully crafted products designed to bring happiness and spiritual warmth to your loved ones and your home.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Gifting', popularity: 390},
    { id : 25, name: 'arvind', thumbnailImage : Gifting7, imges : Gifting7, title : "Gifting & Utsav Collection", description : "Discover the perfect expression of joy and devotion with our Gifting & Utsav Collection. Whether you're marking a special milestone, celebrating a festive occasion, or simply sharing a heartfelt gesture, our curated selection offers thoughtful gifts and essential items to enhance every celebration. Explore a range of beautifully crafted products designed to bring happiness and spiritual warmth to your loved ones and your home.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Gifting', popularity: 390},
    { id : 26, name: 'arvind', thumbnailImage : Gifting8, imges : Gifting8, title : "Gifting & Utsav Collection", description : "Discover the perfect expression of joy and devotion with our Gifting & Utsav Collection. Whether you're marking a special milestone, celebrating a festive occasion, or simply sharing a heartfelt gesture, our curated selection offers thoughtful gifts and essential items to enhance every celebration. Explore a range of beautifully crafted products designed to bring happiness and spiritual warmth to your loved ones and your home.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Gifting', popularity: 390},
    { id : 27, name: 'arvind', thumbnailImage : Gifting9, imges : Gifting9, title : "Gifting & Utsav Collection", description : "Discover the perfect expression of joy and devotion with our Gifting & Utsav Collection. Whether you're marking a special milestone, celebrating a festive occasion, or simply sharing a heartfelt gesture, our curated selection offers thoughtful gifts and essential items to enhance every celebration. Explore a range of beautifully crafted products designed to bring happiness and spiritual warmth to your loved ones and your home.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Gifting', popularity: 390},
    { id : 28, name: 'arvind', thumbnailImage : Gifting10, imges : Gifting10, title : "Gifting & Utsav Collection", description : "Discover the perfect expression of joy and devotion with our Gifting & Utsav Collection. Whether you're marking a special milestone, celebrating a festive occasion, or simply sharing a heartfelt gesture, our curated selection offers thoughtful gifts and essential items to enhance every celebration. Explore a range of beautifully crafted products designed to bring happiness and spiritual warmth to your loved ones and your home.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Gifting', popularity: 390},
    { id : 29, name: 'arvind', thumbnailImage : RitualImg1, imges : RitualImg1, title : "Ritual Essentials (Puja Samagri)", description : "Discover our comprehensive collection of Ritual Essentials, also known as Puja Samagri. We provide high-quality items necessary for performing various Hindu rituals and prayers with devotion and authenticity. From essential ingredients to sacred tools, find everything you need to conduct meaningful and fulfilling pujas.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Ritual', popularity: 390},
    { id : 30, name: 'arvind', thumbnailImage : RitualImg2, imges : RitualImg2, title : "Ritual Essentials (Puja Samagri)", description : "Discover our comprehensive collection of Ritual Essentials, also known as Puja Samagri. We provide high-quality items necessary for performing various Hindu rituals and prayers with devotion and authenticity. From essential ingredients to sacred tools, find everything you need to conduct meaningful and fulfilling pujas.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Ritual', popularity: 390},
    { id : 31, name: 'arvind', thumbnailImage : RitualImg3, imges : RitualImg3, title : "Ritual Essentials (Puja Samagri)", description : "Discover our comprehensive collection of Ritual Essentials, also known as Puja Samagri. We provide high-quality items necessary for performing various Hindu rituals and prayers with devotion and authenticity. From essential ingredients to sacred tools, find everything you need to conduct meaningful and fulfilling pujas.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Ritual', popularity: 390},
    { id : 32, name: 'arvind', thumbnailImage : RitualImg4, imges : RitualImg4, title : "Ritual Essentials (Puja Samagri)", description : "Discover our comprehensive collection of Ritual Essentials, also known as Puja Samagri. We provide high-quality items necessary for performing various Hindu rituals and prayers with devotion and authenticity. From essential ingredients to sacred tools, find everything you need to conduct meaningful and fulfilling pujas.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Ritual', popularity: 390},
    { id : 33, name: 'arvind', thumbnailImage : RitualImg5, imges : RitualImg5, title : "Ritual Essentials (Puja Samagri)", description : "Discover our comprehensive collection of Ritual Essentials, also known as Puja Samagri. We provide high-quality items necessary for performing various Hindu rituals and prayers with devotion and authenticity. From essential ingredients to sacred tools, find everything you need to conduct meaningful and fulfilling pujas.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Ritual', popularity: 390},
    { id : 34, name: 'arvind', thumbnailImage : SacredImg1, imges : SacredImg1, title : " Sacred Powders & Pastes (Chandan-Vibhuti)", description : "Explore our collection of authentic Sacred Powders and Pastes, featuring traditional Chandan (Sandalwood) and Vibhuti (Sacred Ash). These essential elements are integral to Hindu rituals, spiritual practices, and personal adornment, symbolizing purity, devotion, and connection to the divine..", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Sacred', popularity: 390},
    { id : 35, name: 'arvind', thumbnailImage : SacredImg2, imges : SacredImg2, title :  "Sacred Powders & Pastes (Chandan-Vibhuti)", description : "Explore our collection of authentic Sacred Powders and Pastes, featuring traditional Chandan (Sandalwood) and Vibhuti (Sacred Ash). These essential elements are integral to Hindu rituals, spiritual practices, and personal adornment, symbolizing purity, devotion, and connection to the divine.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Sacred', popularity: 390},
    { id : 36, name: 'arvind', thumbnailImage : SacredImg3, imges : SacredImg3, title : "Sacred Powders & Pastes (Chandan-Vibhuti)", description : "Explore our collection of authentic Sacred Powders and Pastes, featuring traditional Chandan (Sandalwood) and Vibhuti (Sacred Ash). These essential elements are integral to Hindu rituals, spiritual practices, and personal adornment, symbolizing purity, devotion, and connection to the divine.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Sacred', popularity: 390},
    { id : 37, name: 'arvind', thumbnailImage : SacredImg4, imges : SacredImg4, title : "Sacred Powders & Pastes (Chandan-Vibhuti)", description : "Explore our collection of authentic Sacred Powders and Pastes, featuring traditional Chandan (Sandalwood) and Vibhuti (Sacred Ash). These essential elements are integral to Hindu rituals, spiritual practices, and personal adornment, symbolizing purity, devotion, and connection to the divine.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Sacred', popularity: 390},
    { id : 38, name: 'arvind', thumbnailImage : SacredImg5, imges : SacredImg5, title : "Sacred Powders & Pastes (Chandan-Vibhuti)", description : "Explore our collection of authentic Sacred Powders and Pastes, featuring traditional Chandan (Sandalwood) and Vibhuti (Sacred Ash). These essential elements are integral to Hindu rituals, spiritual practices, and personal adornment, symbolizing purity, devotion, and connection to the divine.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Sacred', popularity: 390},
    { id : 39, name: 'arvind', thumbnailImage : SacredImg6, imges : SacredImg6, title : "Sacred Powders & Pastes (Chandan-Vibhuti)", description : "Explore our collection of authentic Sacred Powders and Pastes, featuring traditional Chandan (Sandalwood) and Vibhuti (Sacred Ash). These essential elements are integral to Hindu rituals, spiritual practices, and personal adornment, symbolizing purity, devotion, and connection to the divine.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Sacred', popularity: 390},
    { id : 40, name: 'arvind', thumbnailImage : SacredImg7, imges : SacredImg7, title : "Sacred Powders & Pastes (Chandan-Vibhuti)", description : "Explore our collection of authentic Sacred Powders and Pastes, featuring traditional Chandan (Sandalwood) and Vibhuti (Sacred Ash). These essential elements are integral to Hindu rituals, spiritual practices, and personal adornment, symbolizing purity, devotion, and connection to the divine.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'Sacred', popularity: 390},
    { id : 41, name: 'arvind', thumbnailImage : SacredScentsImg1, imges : SacredScentsImg1, title : "Sacred Scents (Sugandh)", description : "Immerse your sacred space in the captivating aromas of our Sacred Scents (Sugandh) collection. Carefully selected for their traditional significance and uplifting fragrances, these scents are ideal for enhancing your prayers, meditation, and spiritual practices, creating a serene and divine atmosphere.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'SacredScents', popularity: 390},
    { id : 42, name: 'arvind', thumbnailImage : SacredScentsImg2, imges : SacredScentsImg2, title : "Sacred Scents (Sugandh)", description : "Immerse your sacred space in the captivating aromas of our Sacred Scents (Sugandh) collection. Carefully selected for their traditional significance and uplifting fragrances, these scents are ideal for enhancing your prayers, meditation, and spiritual practices, creating a serene and divine atmosphere.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'SacredScents', popularity: 390},
    { id : 43, name: 'arvind', thumbnailImage : SacredScentsImg3, imges : SacredScentsImg3, title : "Sacred Scents (Sugandh)", description : "Immerse your sacred space in the captivating aromas of our Sacred Scents (Sugandh) collection. Carefully selected for their traditional significance and uplifting fragrances, these scents are ideal for enhancing your prayers, meditation, and spiritual practices, creating a serene and divine atmosphere.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'SacredScents', popularity: 390},
    { id : 44, name: 'arvind', thumbnailImage : SacredScentsImg4, imges : SacredScentsImg4, title : "Sacred Scents (Sugandh)", description : "Immerse your sacred space in the captivating aromas of our Sacred Scents (Sugandh) collection. Carefully selected for their traditional significance and uplifting fragrances, these scents are ideal for enhancing your prayers, meditation, and spiritual practices, creating a serene and divine atmosphere.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'SacredScents', popularity: 390},
    { id : 45, name: 'arvind', thumbnailImage : SacredScentsImg5, imges : SacredScentsImg5, title : "Sacred Scents (Sugandh)", description : "Immerse your sacred space in the captivating aromas of our Sacred Scents (Sugandh) collection. Carefully selected for their traditional significance and uplifting fragrances, these scents are ideal for enhancing your prayers, meditation, and spiritual practices, creating a serene and divine atmosphere.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'SacredScents', popularity: 390},
    { id : 46, name: 'arvind', thumbnailImage : SacredScentsImg6, imges : SacredScentsImg6, title : "Sacred Scents (Sugandh)", description : "Immerse your sacred space in the captivating aromas of our Sacred Scents (Sugandh) collection. Carefully selected for their traditional significance and uplifting fragrances, these scents are ideal for enhancing your prayers, meditation, and spiritual practices, creating a serene and divine atmosphere.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'SacredScents', popularity: 390},
    { id : 47, name: 'arvind', thumbnailImage : SacredScentsImg7, imges : SacredScentsImg7, title : "Sacred Scents (Sugandh)", description : "Immerse your sacred space in the captivating aromas of our Sacred Scents (Sugandh) collection. Carefully selected for their traditional significance and uplifting fragrances, these scents are ideal for enhancing your prayers, meditation, and spiritual practices, creating a serene and divine atmosphere.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'SacredScents', popularity: 390},
    { id : 48, name: 'arvind', thumbnailImage : SacredScentsImg8, imges : SacredScentsImg8, title : "Sacred Scents (Sugandh)", description : "Immerse your sacred space in the captivating aromas of our Sacred Scents (Sugandh) collection. Carefully selected for their traditional significance and uplifting fragrances, these scents are ideal for enhancing your prayers, meditation, and spiritual practices, creating a serene and divine atmosphere.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'SacredScents', popularity: 390},
    { id : 49, name: 'arvind', thumbnailImage : SringarBoxImg1, imges : SringarBoxImg1, title : "Sringar Box", description : "Our Sringar Box offers a curated collection of beautiful adornments for your beloved deities. Each box is thoughtfully assembled with essential items to enhance the appearance of your idols, adding beauty and reverence to your sacred space.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'SringarBox', popularity: 390},
    { id : 50, name: 'arvind', thumbnailImage : SringarBoxImg2, imges : SringarBoxImg2, title : "Sringar Box", description : "Our Sringar Box offers a curated collection of beautiful adornments for your beloved deities. Each box is thoughtfully assembled with essential items to enhance the appearance of your idols, adding beauty and reverence to your sacred space.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'SringarBox', popularity: 390},
    { id : 51, name: 'arvind', thumbnailImage : SringarBoxImg3, imges : SringarBoxImg3, title : "Sringar Box", description : "Our Sringar Box offers a curated collection of beautiful adornments for your beloved deities. Each box is thoughtfully assembled with essential items to enhance the appearance of your idols, adding beauty and reverence to your sacred space.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'SringarBox', popularity: 390},
    { id : 52, name: 'arvind', thumbnailImage : TempleDecorImg1, imges : TempleDecorImg1, title : "Temple Aromatics & Decor (Mandir Vastu)", description : "Description: Enhance the sanctity and beauty of your home temple with our Temple Aromatics & Decor collection, inspired by Mandir Vastu principles. Discover a range of fragrant items and aesthetically pleasing decor elements designed to create a harmonious and spiritually uplifting environment for your worship.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'TempleDecor', popularity: 390},
    { id : 53, name: 'arvind', thumbnailImage : TempleDecorImg2, imges : TempleDecorImg2, title : "Temple Aromatics & Decor (Mandir Vastu)", description : "Description: Enhance the sanctity and beauty of your home temple with our Temple Aromatics & Decor collection, inspired by Mandir Vastu principles. Discover a range of fragrant items and aesthetically pleasing decor elements designed to create a harmonious and spiritually uplifting environment for your worship.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'TempleDecor', popularity: 390},
    { id : 54, name: 'arvind', thumbnailImage : TempleDecorImg3, imges : TempleDecorImg3, title : "Temple Aromatics & Decor (Mandir Vastu)", description : "Description: Enhance the sanctity and beauty of your home temple with our Temple Aromatics & Decor collection, inspired by Mandir Vastu principles. Discover a range of fragrant items and aesthetically pleasing decor elements designed to create a harmonious and spiritually uplifting environment for your worship.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'TempleDecor', popularity: 390},
    { id : 55, name: 'arvind', thumbnailImage : TempleDecorImg4, imges : TempleDecorImg4 , title : "Temple Aromatics & Decor (Mandir Vastu)", description : "Description: Enhance the sanctity and beauty of your home temple with our Temple Aromatics & Decor collection, inspired by Mandir Vastu principles. Discover a range of fragrant items and aesthetically pleasing decor elements designed to create a harmonious and spiritually uplifting environment for your worship.", price : 180, size : "27 x 17 x 8 cm" ,createdAt: '2024-08-30',category: 'TempleDecor', popularity: 390},
]

export default Product